# Generated by Django 4.1.1 on 2022-09-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('preco', models.DateField(verbose_name='preço')),
                ('estoque', models.IntegerField(verbose_name='qtd em estoque')),
            ],
        ),
    ]
